[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "gnn-benchmark"
version = "0.1.0"
dependencies = ["pandas", "numpy", "gdown"]

[tool.setuptools]
packages = [
    "gnn_benchmark",
    "gnn_benchmark.core",
    "gnn_benchmark.datasets",
    "gnn_benchmark.models",
    "gnn_benchmark.models.MTGODE",
    "gnn_benchmark.models.STAEFormer",
    "gnn_benchmark.models.STAEFormer.model",
    "gnn_benchmark.tuning",
    "gnn_benchmark.utils",
]

[tool.setuptools.package-dir]
"gnn_benchmark" = "."
